In [2]:
import numpy as np
matrix = np.array([[1,0.2,0.5],[0.2,1,0.8],[0.5,0.8,1]])
print(matrix)

[[1.  0.2 0.5]
 [0.2 1.  0.8]
 [0.5 0.8 1. ]]


In [3]:

transposed_matrix = np.transpose(matrix)
print("\nTransposed Matrix:")
print(transposed_matrix)


Transposed Matrix:
[[1.  0.2 0.5]
 [0.2 1.  0.8]
 [0.5 0.8 1. ]]


In [4]:
inverse_transposed_matrix = np.linalg.inv(transposed_matrix)
print("\nInverse of the Transposed Matrix:")
print(inverse_transposed_matrix)


Inverse of the Transposed Matrix:
[[ 1.56521739  0.86956522 -1.47826087]
 [ 0.86956522  3.26086957 -3.04347826]
 [-1.47826087 -3.04347826  4.17391304]]


In [5]:

#The determinant
determinant = np.linalg.det(matrix)
print("Determinant of the matrix:", determinant)


Determinant of the matrix: 0.2299999999999999


In [3]:
# using LU Decomposition
import numpy as np
from scipy.linalg import lu

#matrix 
matrix = np.array([[1,0.2,0.5],[0.2,1,0.8],[0.5,0.8,1]])


# Perform LU Decomposition
P, L, U = lu(matrix)

# Display results
print("LU Decomposition:")
print("P (Permutation matrix):\n", P)
print("L (Lower triangular matrix):\n", L)
print("U (Upper triangular matrix):\n", U)

ModuleNotFoundError: No module named 'scipy'

In [1]:

#matrix
import numpy as np

matrix = np.array([[1,0.2,0.5],[0.2,1,0.8],[0.5,0.8,1]])

# Scale the matrix by a scalar k = 2
scaled_matrix = 2 * matrix

print("Original Matrix:")
print(matrix)

print("\nScaled Matrix (k=2):")
print(scaled_matrix)


Original Matrix:
[[1.  0.2 0.5]
 [0.2 1.  0.8]
 [0.5 0.8 1. ]]

Scaled Matrix (k=2):
[[2.  0.4 1. ]
 [0.4 2.  1.6]
 [1.  1.6 2. ]]
